name: bank_campaign_conversion
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.10.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.3
  - cuda-version=12.9
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - executing=2.2.1
  - expat=2.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fs=2.4.16
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=11.0.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=75.1
  - idna=3.11
  - imbalanced-learn=0.14.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.4
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=3.1.1
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mkl=2025.3.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numpy=2.3.4
  - openjpeg=2.5.3
  - openssl=3.6.0
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pathlib=1.0.1
  - patsy=1.0.2
  - pcre2=10.44
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-xgboost=3.1.1
  - pycparser=2.23
  - pygments=2.19.1
  - pyparsing=3.2.5
  - pyprojroot=0.3.0
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xgboost=3.1.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - bank-campaign-conversion==0.1.0
      - duckdb==1.4.1
      - pyhere==1.0.3
      - scipy==1.16.3
prefix: C:\Users\ASUS TUF\.conda\envs\bank_campaign_conversion
